
// Generated by the mtime code generator.  DO NOT EDIT!
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

package mfw.index.search.service.constant;
import mfw.index.search.service.dto.SearchDto.*;

	/**
	 * 后台通用搜索服务
	 * mscgenVersion: 0.4.4
	**/
public interface SearchService {

	
	/**
	 * 搜索
	 * @param request
	 * @return
	**/
	SearchResponse search(SearchRequest request);
	
	/**
	 * 全量搜索
	 * @param request
	 * @return
	**/
	ScrollSearchResponse scrollSearch(ScrollSearchRequest request);
	
	/**
	 * 建索引
	 * @param request
	 * 
	**/
	void index(IndexRequest request);
	
	/**
	 * 释放scroll
	 * @param request
	 * 
	**/
	void closeScroll(CloseScrollRequest request);
	
}
	